component Stats			   " Компонент который собирает статистику";
		
pin in bit PrgRUN;				// Сигнал программа в работе
pin in bit Torch;				// Torch on/off
pin in bit ArcOK;				// Состояние дуги
pin in bit DI;					// Сигнал цифровой выход 00 (расчёт количества пробивок)
pin in bit DIprobeTime;			// Сигнал цифровой выход 01 (расчёт количества времени )
pin in  float current_velocity; // current machine velocity, подключить к motion.current-vel
pin out float cut_time;			// Время реза
pin out float cut_length;		// Длинна реза
pin out s32 	pierce_count; 	// Количество пробивок
pin out s32     state_out;		// Этапы работы панели статистики

variable bool   pierce_count_flag = false;	//Флаг для счёта пробивок



	

option singleton yes;				   // только один экземпляр компонента может быть запущен
function _;  							//function _ fp;
author "treyne";
license "GPL";
;;



FUNCTION(_)
{
		if (!PrgRUN){state_out=0;}
		if (Torch) {state_out=6;}else{if (DIprobeTime) {state_out=1;}}

		if (DI){pierce_count_flag = true;}
		if (!DI && pierce_count_flag) {pierce_count += 1; pierce_count_flag = false;}
		
		if (Torch && ArcOK && PrgRUN){	cut_time = cut_time + fperiod;
										cut_length = cut_length + current_velocity * fperiod;
										} else {" SOME CODE";} 
		   
}
